### ISSUE TITLE
Add method to download multiple variants at once

### ISSUE THREAD

**Issue by TazeXL** [itsgeagle/caiedownloader#10]
Add capability to:
- Choose 2 or 3 types of paper to be downloaded together 
- Choose whether to save in two files, or concatenate into one

Something like this: 
![image](https://github.com/itsgeagle/caiedownloader/assets/108285666/d65f158a-f09c-455f-b7b3-642f0527da6a)

**Comment by TazeXL** [comment]
![image](https://github.com/itsgeagle/caiedownloader/assets/108285666/c99df902-ca99-437b-8700-8b99e72bddb0)

**Comment by itsgeagle** [comment]
Fixed in #16
