### ISSUE TITLE
umm i am getting this error any fix?

### ISSUE THREAD

**Issue by icloudxpringly** [itsgeagle/caiedownloader#24]
![image](https://github.com/itsgeagle/caiedownloader/assets/166696237/85d13983-cef5-4e51-860f-12ee32f6ee52)
any fix?, i have installed all requirements and i have python 3.11 *working*

**Comment by itsgeagle** [comment]
You have a missing DLL file. Follow the steps given here - https://github.com/pymupdf/PyMuPDF/issues/2678#issuecomment-1730662415

**Comment by itsgeagle** [comment]
For a more detailed guide, read here - https://github.com/pymupdf/PyMuPDF/blob/main/docs/installation.rst#problems-after-installation
